# Generated by Django 5.2.12 on 2026-03-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]


    def enter_new_building(apps, schema_editor):
        flat = apps.get_model('property', 'Flat')
        for flat in flat.objects.all():
            if flat.construction_year > 2014:
                flat.new_building = True
                flat.save()
            else:
                flat.new_building = False
                flat.save()



    operations = [
        migrations.RunPython(enter_new_building),
    ]
