# Generated by Django 5.2.12 on 2026-03-15 10:24

from django.db import migrations
import phonenumbers


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_owner_pure_phone'),
    ]


    def enter_owner_pure_phone(apps, schema_editor):
        flat = apps.get_model('property', 'Flat')
        for flat in flat.objects.all():
            phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(phone_number):
                flat.owner_pure_phone = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.E164)
                flat.save()


    operations = [
        migrations.RunPython(enter_owner_pure_phone),
    ]
