# Generated by Django 5.2.12 on 2026-03-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]


    def create_owners(apps, schema_editor):
        flat = apps.get_model('property', 'Flat')
        owner = apps.get_model('property', 'Owner')
        for flat in flat.objects.all().iterator():
            owner.objects.get_or_create(
                name=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=flat.owner_pure_phone
            )




    operations = [
        migrations.RunPython(create_owners),
    ]
