# Generated by Django 5.2.12 on 2026-03-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_flat_owner_alter_flat_owner_pure_phone_and_more'),
    ]


    def enter_flats(apps, schema_editor):
        flat = apps.get_model('property', 'Flat')
        owner = apps.get_model('property', 'Owner')
        for owner in owner.objects.all():
            flat_entities = flat.objects.filter(owner_pure_phone=owner.pure_phonenumber)
            for flat_entity in flat_entities:
                owner.flat.add(flat_entity.id)
                owner.save()


    operations = [
        migrations.RunPython(enter_flats),
    ]
